CREATE OR REPLACE FUNCTION API_TOKEN(PSECRET VARCHAR2) RETURN VARCHAR2
IS
    VRESULT VARCHAR2(4000);
BEGIN
        SELECT ULT_RAW.CAST_TO_VARCHAR2(ULT_I18N.STRING_TO_RAW(STANDARD_HASH(PSECRET, 'MDS'), 'AL32UTF8')) INTO VRESULT from dual;
        RETURN VRESULT;
END API_TOKEN;